version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: cmport_db
    restart: always
    environment:
      MYSQL_DATABASE: cmport_gerenciamento
      MYSQL_ROOT_PASSWORD: cmport2026
      MYSQL_USER: cmport
      MYSQL_PASSWORD: cmport123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"  # Você acessará por http://localhost:8080
    depends_on:
      - db           # Garante que o Adminer só suba após o banco estar pronto

  minio:
    image: minio/minio:latest
    container_name: cmport_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"   # API S3-compatível
      - "9001:9001"   # Console web (http://localhost:9001)
    volumes:
      - minio_data:/data

volumes:
  db_data:
  minio_data:
